package client;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import client.Threading.ServerThread;

/**
 *
 * @author vishalgupta
 */
public class Registration extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private ServerThread thread;

    /**
     * Creates new form Registration
     */
    public Registration(ServerThread thread, Client client) {
        this.thread = thread;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        registrationFormPanel = new javax.swing.JPanel();
        forgotPasswordButton = new javax.swing.JButton();
        registrationButton = new javax.swing.JButton();
        passwordField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        registrationFormPanel.setBackground(new java.awt.Color(204, 255, 255));

        forgotPasswordButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        forgotPasswordButton.setForeground(new java.awt.Color(255, 153, 0));
        forgotPasswordButton.setText("Forgot Password");

        registrationButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        registrationButton.setForeground(new java.awt.Color(255, 153, 0));
        registrationButton.setText("Register");
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(102, 102, 0));
        passwordLabel.setLabelFor(passwordField);
        passwordLabel.setText("Enter a Password:");

        usernameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(102, 102, 0));
        usernameLabel.setLabelFor(usernameField);
        usernameLabel.setText("Enter a Username:");

        javax.swing.GroupLayout registrationFormPanelLayout = new javax.swing.GroupLayout(registrationFormPanel);
        registrationFormPanel.setLayout(registrationFormPanelLayout);
        registrationFormPanelLayout.setHorizontalGroup(
            registrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationFormPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(registrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel)
                    .addComponent(usernameLabel))
                .addGap(44, 44, 44)
                .addGroup(registrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationFormPanelLayout.createSequentialGroup()
                        .addComponent(forgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registrationFormPanelLayout.createSequentialGroup()
                        .addGroup(registrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField)
                            .addComponent(usernameField)
                            .addGroup(registrationFormPanelLayout.createSequentialGroup()
                                .addComponent(registrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 142, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))))
        );
        registrationFormPanelLayout.setVerticalGroup(
            registrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationFormPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(registrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(registrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        add(registrationFormPanel);
        registrationFormPanel.setBounds(36, 160, 548, 291);

        logoLabel.setIcon(new javax.swing.ImageIcon("/Users/vishalgupta/Desktop/Software engeenering/side4-01.jpeg")); // NOI18N
        add(logoLabel);
        logoLabel.setBounds(36, 6, 229, 142);

        titleLabel.setBackground(new java.awt.Color(255, 153, 153));
        titleLabel.setFont(new java.awt.Font("Marker Felt", 0, 72)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 153, 204));
        titleLabel.setText("The BOX");
        add(titleLabel);
        titleLabel.setBounds(271, 69, 248, 79);

        usernameField.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    passwordField.requestFocusInWindow();
                }
            }
        });
        passwordField.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (passwordField.toString().isEmpty() || usernameField.getText().isEmpty())
                        usernameField.requestFocusInWindow();
                    else
                    registrationButtonActionPerformed(null);
                }
            }
        });
    }// </editor-fold>                        
    
    private void registrationButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String username = usernameField.getText();
        String pass = String.valueOf(passwordField.getText());
        thread.checkRegistration(username, pass);
    }

    public void handleRegistrationReq(int opcode) {
         // TO DO
    
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton forgotPasswordButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registrationButton;
    private javax.swing.JPanel registrationFormPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration                   
}